In [1]:
import pandas as pd

In [2]:
df_ingressos_familia = pd.read_csv("./raw_data/pesquisa-permanente-lares/registros/INGREFAM_EPHC_ANUAL_2024.csv",delimiter=";")

/var/folders/41/qn903nd549s1fcqkqz80hxl00000gn/T/ipykernel_30941/2010732076.py:1: DtypeWarning: Columns (0: e01lde) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ingressos_familia = pd.read_csv("./raw_data/pesquisa-permanente-lares/registros/INGREFAM_EPHC_ANUAL_2024.csv",delimiter=";")

In [3]:
df_ingressos_familia.head()

,upm,nvivi,nhoga,dpto,area,año,e01aimde,e01bimde,e01cimde,e01dde,...,p1pobtot,p2pobtot,p0pobext,p1pobext,p2pobext,ipcmdefg,quintili,decili,quintiai,decilai
0,14,3,1,0,1,2024,"7077708,07786259",0,0,0,...,,0,0,,0,"4035459,49658286",5,10,5,9
1,14,15,1,0,1,2024,0,0,0,0,...,,0,0,,0,"1782061,06870229",4,7,3,6
2,14,23,1,0,1,2024,"9826793,89312976",0,0,0,...,,0,0,,0,"5931717,5572519",5,10,5,10
3,14,26,1,0,1,2024,"7433740,45801526",0,0,0,...,,0,0,,0,"3716870,22900763",5,9,5,9
4,14,33,1,0,1,2024,"5198526,71755725","1629312,97709923",0,0,...,,0,0,,0,"3413919,84732824",5,9,5,9

In [6]:
df_ingressos_familia.columns

Index(['upm', 'nvivi', 'nhoga', 'dpto', 'area', 'año', 'e01aimde', 'e01bimde',
       'e01cimde', 'e01dde', 'e01ede', 'e01fde', 'e02tde', 'e01hide', 'e01ide',
       'e01jde', 'e01kjde', 'e01hde', 'e01kde', 'e01lde', 'v19ede',
       'ingrevasode', 'ingrealmuerzode', 'v21gde', 'totpers', 'ingrem', 'ipcm',
       'linpobto', 'linpobex', 'pobrezai', 'pobnopoi', 'fex.2022', 'facpob',
       'p0pobtot', 'p1pobtot', 'p2pobtot', 'p0pobext', 'p1pobext', 'p2pobext',
       'ipcmdefg', 'quintili', 'decili', 'quintiai', 'decilai'],
      dtype='str')

In [9]:
df_ingressos_familia.describe()

,upm,nvivi,nhoga,dpto,area,año,ingrevasode,ingrealmuerzode,totpers,linpobto,linpobex,pobrezai,pobnopoi,p0pobtot,p0pobext,quintili,decili,quintiai,decilai
count,17242.000000,17242.000000,17242.000000,17242.000000,17242.000000,17242.0,17242.000000,1.724200e+04,17242.000000,17242.000000,17242.000000,17242.000000,17242.000000,17242.000000,17242.000000,17242.000000,17242.000000,17242.000000,17242.000000
mean,14700.166744,32.728570,1.000986,7.651955,3.158102,2024.0,15972.247303,4.966940e+04,3.341492,792495.290222,377217.609442,2.794629,0.172544,0.172544,0.032827,3.156188,5.833198,3.210068,5.934114
std,8631.564512,24.322342,0.034886,4.329066,2.476583,0.0,39662.347764,1.582424e+05,1.775643,120119.707733,16842.248071,0.478394,0.377863,0.377863,0.178188,1.438296,2.927049,1.425104,2.902043
min,14.000000,1.000000,1.000000,0.000000,1.000000,2024.0,0.000000,0.000000e+00,1.000000,654657.000000,357891.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,7250.000000,15.000000,1.000000,4.000000,1.000000,2024.0,0.000000,0.000000e+00,2.000000,654657.000000,357891.000000,3.000000,0.000000,0.000000,0.000000,2.000000,3.000000,2.000000,3.000000
50%,14136.000000,30.000000,1.000000,8.000000,1.000000,2024.0,0.000000,0.000000e+00,3.000000,897168.000000,391894.000000,3.000000,0.000000,0.000000,0.000000,3.000000,6.000000,3.000000,6.000000
75%,22464.000000,46.000000,1.000000,11.000000,6.000000,2024.0,0.000000,0.000000e+00,4.000000,897168.000000,391894.000000,3.000000,0.000000,0.000000,0.000000,4.000000,8.000000,5.000000,9.000000
max,28774.000000,975.000000,3.000000,15.000000,6.000000,2024.0,523344.000000,3.379211e+06,27.000000,897168.000000,391894.000000,3.000000,1.000000,1.000000,1.000000,5.000000,10.000000,5.000000,10.000000

In [ ]:

df_ingressos_familia[['e01aimde', 'ingrem','ipcm', "decilai"]].sort_values(by="decilai")

               e01aimde            ingrem              ipcm  decilai
5011                  0  1398951,31086142  699475,655430709        1
5565   1247916,66666667  2887916,66666667  721979,166666667        1
5564   153333,333333333  1603333,33333333  534444,444444445        1
16390  999250,936329584  1548838,95131086  516279,650436952        1
7053   155814,897302648  1246436,86686464   311609,21671616        1
...                 ...               ...               ...      ...
5581                  0           2860000           2860000       10
5580   24275833,3333333  28275833,3333333  9425277,77777778       10
15470  5862421,52466365  6959133,03437964  3479566,51718982       10
11380  9903489,23533781  14813969,3145261  3703492,32863153       10
17241   2490664,6751307  2958416,83048543  2958416,83048543       10

[17242 rows x 4 columns]

In [ ]:
df_ingressos_familia[df_ingressos_familia['dpto'] == 0]['']

,upm,nvivi,nhoga,dpto,area,año,e01aimde,e01bimde,e01cimde,e01dde,...,p1pobtot,p2pobtot,p0pobext,p1pobext,p2pobext,ipcmdefg,quintili,decili,quintiai,decilai
0,14,3,1,0,1,2024,"7077708,07786259",0,0,0,...,,0,0,,0,"4035459,49658286",5,10,5,9
1,14,15,1,0,1,2024,0,0,0,0,...,,0,0,,0,"1782061,06870229",4,7,3,6
2,14,23,1,0,1,2024,"9826793,89312976",0,0,0,...,,0,0,,0,"5931717,5572519",5,10,5,10
3,14,26,1,0,1,2024,"7433740,45801526",0,0,0,...,,0,0,,0,"3716870,22900763",5,9,5,9
4,14,33,1,0,1,2024,"5198526,71755725","1629312,97709923",0,0,...,,0,0,,0,"3413919,84732824",5,9,5,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1264,2181,87,1,0,1,2024,4700000,1440000,0,0,...,,0,0,,0,"1477047,6",3,5,3,5
1265,2181,103,1,0,1,2024,6550000,0,0,0,...,,0,0,,0,"1805654,75",4,7,3,6
1266,2181,111,1,0,1,2024,0,0,0,0,...,",349805907774984",",12236417311428",0,,0,"583333,333333333",1,2,1,1
1267,2181,116,1,0,1,2024,3400000,0,0,0,...,,0,0,,0,"1236309,5",2,4,2,4
1268,2181,117,1,0,1,2024,6300000,0,0,0,...,,0,0,,0,"1502333,33333333",3,6,3,5

In [16]:
print(1398951/6450)
print(31086142/6450)

216.89162790697674
4819.556899224806

In [13]:
1398951,31086142

(1398951, 31086142)

In [14]:
manual = pd.read_excel("./raw_data/pesquisa-permanente-lares/ingresso/diccionario_EPHC_ANUAL_2024.xls")

ImportError: `Import xlrd` failed. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install the xlrd package.

In [ ]:
!pip install xlrd